version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - assetm-network

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    networks:
      - assetm-network
    depends_on:
      - client

networks:
  assetm-network:
    driver: bridge